name: "Building and Pushing Docker Image"

on:
  workflow_call:
    inputs:
      image_name:
        description: "Name of the image"
        required: true
        type: string
      tag:
        description: "Tag for the image"
        required: true
        type: number
      registry_username:
        description: "Username of Docker"
        required: true
        type: string
      registry_password: 
        description: "Password for Docker"
        required: true
        type: string

jobs:
  job1:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup BuildX
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          username: ${{inputs.registry_username}}
          password: ${{inputs.registry_password}}

      - name: Build and push Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{inputs.registry_username}}/${{inputs.image_name}}:${{inputs.tag}}

  job2:
    name: Print name
    runs-on: ubuntu-latest
    steps:
    - run: echo "Hello my name is Ronak"